export const team = [
  {
    id: 1,
    name: 'Daria Serhiienko',
    position: 'Designer',
    image: 'SERHIIENKO',
    social: {
      behance: 'https://www.behance.net/dariaserhiienko',
      dribble: 'https://dribbble.com/dariaSerhiienko',
      github: '',
      linkedin: '',
    },
  },
  {
    id: 2,
    name: 'Artem Mytrofanov',
    position: 'QA',
    image: 'MYTROFANOV',
    social: {
      behance: '',
      dribble: '',
      github: 'https://github.com/mitrofin',
      linkedin: 'https://www.linkedin.com/in/artem-mytrofanov/',
    },
  },
  {
    id: 3,
    name: 'Vitalii Filchenko',
    position: 'Front-End Developer',
    image: 'MYTROFANOV',
    social: {
      behance: '',
      dribble: '',
      github: 'https://github.com/FortizFil',
      linkedin: 'https://www.linkedin.com/in/vitalii-filchenko/',
    },
  },
  {
    id: 4,
    name: 'Oksana Kuznietsova',
    position: 'Front-End Developer',
    image: 'KUZNIETSOVA',
    social: {
      behance: '',
      dribble: '',
      github: 'https://github.com/KuznietsovaOksana',
      linkedin: 'https://www.linkedin.com/in/oksana-kuznietsova/',
    },
  },
  {
    id: 5,
    name: 'Anna Gubarieva',
    position: 'Front-End Developer',
    image: 'GUBARIEVA',
    social: {
      behance: '',
      dribble: '',
      github: 'https://github.com/GubarievaAnna',
      linkedin: 'https://www.linkedin.com/in/anna-gubarieva/',
    },
  },
  {
    id: 6,
    name: 'Vita Kostiuk',
    position: 'Front-End Developer',
    image: 'KOSTIUK',
    social: {
      behance: '',
      dribble: '',
      github: 'https://github.com/vitakostiuk',
      linkedin: 'https://www.linkedin.com/in/vitakostiuk',
    },
  },
  {
    id: 7,
    name: 'Ihor Khabuzov',
    position: 'Front-End Developer',
    image: 'KHABUZOV',
    social: {
      behance: '',
      dribble: '',
      github: 'https://github.com/egarra',
      linkedin: 'https://www.linkedin.com/in/ihor-khabuzov-53a76825b/',
    },
  },
  {
    id: 8,
    name: 'Aleksander Nikolaenko',
    position: 'Front-End Developer',
    image: 'NIKOLAENKO',
    social: {
      behance: '',
      dribble: '',
      github: 'https://github.com/aleksander-nikolaenko',
      linkedin: 'https://www.linkedin.com/in/aleksander-nikolaienko/',
    },
  },
  {
    id: 9,
    name: 'Vitalii Kretsul',
    position: 'Front-End Developer',
    image: 'KRETSUL',
    social: {
      behance: '',
      dribble: '',
      github: 'https://github.com/Kretsul-Vitaliy',
      linkedin: 'https://www.linkedin.com/in/vitalii-kretsul-442213b6/',
    },
  },
  {
    id: 10,
    name: 'Vlad Moskalenko',
    position: 'Front-End Developer',
    image: 'MOSKALENKO',
    social: {
      behance: '',
      dribble: '',
      github: 'https://github.com/Vlad-Moskalenko/',
      linkedin: 'https://www.linkedin.com/in/vlad-moskalenko/',
    },
  },
  {
    id: 2,
    name: 'Daria Serhiienko',
    position: 'Designer',
    image: 'SERHIIENKO',
    social: {
      behance: 'https://www.behance.net/dariaserhiienko',
      dribble: 'https://dribbble.com/dariaSerhiienko',
      github: '',
      linkedin: '',
    },
  },
  {
    id: 3,
    name: 'Artem Mytrofanov',
    position: 'QA',
    image: 'MYTROFANOV',
    social: {
      behance: '',
      dribble: '',
      github: 'https://github.com/mitrofin',
      linkedin: 'https://www.linkedin.com/in/artem-mytrofanov/',
    },
  },
  {
    id: 4,
    name: 'Oksana Kuznietsova',
    position: 'Front-End Developer',
    image: 'KUZNIETSOVA',
    social: {
      behance: '',
      dribble: '',
      github: 'https://github.com/KuznietsovaOksana',
      linkedin: 'https://www.linkedin.com/in/oksana-kuznietsova/',
    },
  },
  {
    id: 5,
    name: 'Anna Gubarieva',
    position: 'Front-End Developer',
    image: 'GUBARIEVA',
    social: {
      behance: '',
      dribble: '',
      github: 'https://github.com/GubarievaAnna',
      linkedin: 'https://www.linkedin.com/in/anna-gubarieva/',
    },
  },
  {
    id: 6,
    name: 'Vita Kostiuk',
    position: 'Front-End Developer',
    image: 'KOSTIUK',
    social: {
      behance: '',
      dribble: '',
      github: 'https://github.com/vitakostiuk',
      linkedin: 'https://www.linkedin.com/in/vitakostiuk',
    },
  },
  {
    id: 7,
    name: 'Ihor Khabuzov',
    position: 'Front-End Developer',
    image: 'KHABUZOV',
    social: {
      behance: '',
      dribble: '',
      github: 'https://github.com/egarra',
      linkedin: 'https://www.linkedin.com/in/ihor-khabuzov-53a76825b/',
    },
  },
  {
    id: 8,
    name: 'Aleksander Nikolaenko',
    position: 'Front-End Developer',
    image: 'NIKOLAENKO',
    social: {
      behance: '',
      dribble: '',
      github: 'https://github.com/aleksander-nikolaenko',
      linkedin: 'https://www.linkedin.com/in/aleksander-nikolaienko/',
    },
  },
  {
    id: 9,
    name: 'Vitalii Kretsul',
    position: 'Front-End Developer',
    image: 'KRETSUL',
    social: {
      behance: '',
      dribble: '',
      github: 'https://github.com/Kretsul-Vitaliy',
      linkedin: 'https://www.linkedin.com/in/vitalii-kretsul-442213b6/',
    },
  },
  {
    id: 10,
    name: 'Vlad Moskalenko',
    position: 'Front-End Developer',
    image: 'MOSKALENKO',
    social: {
      behance: '',
      dribble: '',
      github: 'https://github.com/Vlad-Moskalenko/',
      linkedin: 'https://www.linkedin.com/in/vlad-moskalenko/',
    },
  },
];
